PL/Models/ErrorViewModel.cs
namespace PL.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

PL/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using PL.Models;
using System.Diagnostics;

namespace PL.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

PL/Controllers/PersonaController.cs
using Microsoft.AspNetCore.Mvc;
using ML;

namespace PL.Controllers
{
    public class PersonaController : Controller
    {
        [HttpGet]

        public ActionResult GetAll()
        {

            string RutaTxt = @"C:/Users/digis/OneDrive/Documents/Jesus Francisco Rodriguez Martinez/JRodriguezExamenSegurosAzteca/PL/wwwroot/Archivos/nombres.txt";

            ML.Persona persona = new ML.Persona();
            List<object> Personas = new List<object>();

            List<string> Nombres = new List<string>();
            List<string> NombresOrden = new List<string>();

            using (StreamReader sr = new StreamReader(RutaTxt))
            {
                string linea;
                while ((linea = sr.ReadLine()) != null)
                {
                    string[] nombres = linea.Split(','); //Para obtener un nombre del txt cada que encuentre una ,

                    foreach (string nombre in nombres)
                    {
                        Nombres.Add(nombre.Trim());
                    }

                    NombresOrden = Nombres.OrderBy(n => n).ToList();//LISTA EN ORDEN ALFABETICO(LINQ)

                    foreach (string nombre in NombresOrden)
                    {
                        persona = new ML.Persona();
                        persona.Nombre = nombre;

                        Personas.Add(persona);

                    }
                }
            }


            persona.Personas = Personas;
            return View(persona);
        }

        [HttpGet]

        public ActionResult Puntuacion(string Nombre)
        {
            //Eliminar comillas de de la cadena o nombre
            char[] CharAeliminar = { '"' };
            string NombreLimpio = Nombre.Trim(CharAeliminar);//Trim permite eliminar o alterar una cadena 

            //Alfabeto arreglo
            char[] Alfabeto = new char[26];

            for (int i = 0; i < 26; i++)
            {
                Alfabeto[i] = (char)('A' + i);
            }

            //Obtener puntuacion del nombre segun el arreglo alfabeto
            int[] Indices = new int[NombreLimpio.Length];

            for (int i = 0; i < NombreLimpio.Length; i++)
            {
                char letra = NombreLimpio[i];//recorremos el nombre letra por letra
                Indices[i] = Array.IndexOf(Alfabeto, letra) + 1;//obtenemos el indice segun la letra del nombre y el arreglo alfabeto
            }

            //Obtenemos la lista de los nombres ordenados alfabeticamente
            List<string> Nombres = ObtenerListaPersonas();


            int IdiceNombre = Nombres.IndexOf(Nombre) + 1;//Indice del nombre en la lista

            int PuntacionIndices = Indices.Sum();//suma de indices del nombre

            int PuntuacionTotal = IdiceNombre * PuntacionIndices;

            ViewBag.Message = "La puntuacion del nombre: " + Nombre + " es de " + PuntuacionTotal;
            return PartialView("Modal");
        }

        public List<string> ObtenerListaPersonas()
        {
            string RutaTxt = @"C:/Users/digis/OneDrive/Documents/Jesus Francisco Rodriguez Martinez/JRodriguezExamenSegurosAzteca/PL/wwwroot/Archivos/nombres.txt";

            ML.Persona persona = new ML.Persona();
            List<object> Personas = new List<object>();

            List<string> Nombres = new List<string>();
            List<string> NombresOrden = new List<string>();

            using (StreamReader sr = new StreamReader(RutaTxt))
            {
                string linea;
                while ((linea = sr.ReadLine()) != null)
                {
                    string[] nombres = linea.Split(','); //Para obtener un nombre del txt cada que encuentre una ,

                    foreach (string nombre in nombres)
                    {
                        Nombres.Add(nombre.Trim());
                    }
                    NombresOrden = Nombres.OrderBy(n => n).ToList();//LISTA EN ORDEN ALFABETICO(LINQ)
                }
            }
            return NombresOrden;
        }
    }
}

PL/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

PL/Views/Persona/GetAll.cshtml
@model ML.Persona
@{
    ViewData["Title"] = "GetAll";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Nombres ordenados Alfabeticamente</h1>

<table class="table table-hover table-striped table-bordered table-responsive" id="TablaNombres">
    <thead>
        <tr class="table-secondary">
            <td style="text-align:center">Nombre</td>
            <td style="text-align:center">Calcular Puntuacion</td>
        </tr>
    </thead>

    <tbody>
        @foreach (ML.Persona persona in Model.Personas)
        {
            <tr>
                <td style="text-align:center">@persona.Nombre</td>
                <td style="text-align:center; vertical-align:middle"><a class="btn btn-warning" href="@Url.Action("Puntuacion","Persona", new{Nombre = persona.Nombre})"></a></td>
            </tr>
        }
    </tbody>
</table>


@section Scripts {
    <script src="https://code.jquery.com/jquery-3.5.1.js"></script>
    <script src="https://cdn.datatables.net/1.13.1/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.13.1/js/dataTables.material.min.js"></script>
    <script src="https://cdn.datatables.net/1.13.1/js/dataTables.bootstrap5.min.js"></script>

    <script type="text/javascript">
        $(document).ready(function () {
            $('#TablaNombres').DataTable({
                searching: false,
                "lengthMenu": [[5, 10, 15, 20, -1], [5, 10, 15, 20, "All"]],
                autoWidth: false,
                columnDefs: [
                    {
                        targets: ['_all'],
                        className: 'mdc-data-table__cell',
                    },
                ],
                language: {
                    url: "//cdn.datatables.net/plug-ins/9dcbecd42ad/i18n/Spanish.json",
                },
            });
        });

    </script>
        }

PL/Views/Persona/Modal.cshtml
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script src="http://bootboxjs.com/bootbox.js"></script>
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

<div class="modal" tabindex="-1" role="dialog" id="Modal">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Aviso</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <h5 style="text-align:center">@ViewBag.Message</h5>
            </div>
            <div class="modal-footer">
                @*@Html.ActionLink("Regresar", "GetAll", "Materia", htmlAttributes: new { @class = "btn btn-danger" })*@
                @Html.ActionLink("Vale", "GetAll", "Persona", htmlAttributes: new { @class = "btn btn-danger" })


            </div>
        </div>
    </div>
</div>

<script>
    $('#Modal').modal();
</script>

PL/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PL</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/PL.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">PL</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Persona" asp-action="GetAll">Personas</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - PL - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>